### PR TITLE
add declaration & types test for typescript

### PR DESCRIPTION
**Pull request by Keyj1n**

### CODE REVIEW

**Comment by alisd23** [comment]
Hey tests are failing. Could you check it out? I assume it's related to the changes, as master passed recently.

**Comment by alisd23** [comment]
Never mind, master is also failing. Looks like one of the dependencies might have introduced a breaking change without a major version bump...

**Comment by Keyj1n** [comment]
done. 
np :)

**Comment by alisd23** [comment]
OK merged, thanks again @Keyj1n 👍

**Pull request merged**
