### PR TITLE
fixes #13

### LINKED ISSUE #13: [TS] IComplexType missing
IComplexType got removed from `mobx-state-tree` in https://github.com/mobxjs/mobx-state-tree/commit/c300c798732591e96c006433bd367319ab77eb41.
By the looks of it, it now is replaced by simply using `IType`.
I'll open a PR soon.

### PR DESCRIPTION
**Pull request by freund17**
Fixes https://github.com/alisd23/mst-react-router/issues/13

### CODE REVIEW

**Comment by alisd23** [comment]
Hey thanks for this. Just to double check, have you played around with this locally? Tests are passing so I will merge soon if you're confident. 👍

**Comment by freund17** [comment]
Well, I tested it - and it works - in the current version of `mobx-state-tree`.
But I suspect there to be wrong behavior in versions before https://github.com/mobxjs/mobx-state-tree/commit/c300c798732591e96c006433bd367319ab77eb41.
Possibly `mobx-state-tree@3.8.0`?

That theory being correct, this is probably a **breaking change** for TypeScript users using an older version of mobx-state-tree than 3.8.0.

Ideally we would check for the existence of `IComplexType` in `mobx-state-tree`; And only if it doesn't exist use `IType`. But I have no idea how to conditionally check for the existence of a type.

Maybe @xaviergonz could shed some light on the implications of his change.
As his commit wasn't versioned as a breaking change, we might be using the wrong api/types in the first place?

**Comment by xaviergonz** [comment]
I can just add type IComplexType on mst as alias for IType if that helps with backward compatibility

**Comment by freund17** [comment]
@xaviergonz First of all I would like you to have a look at the types we used in https://github.com/alisd23/mst-react-router/blob/da51a065e832525e41d8cff73bcf2a05e651dc77/types.d.ts.
Simply to make sure that we did not misuse something (using internal types / the wrong generics; hell, I don't know :P )

If that's all correct, and IComplexType *was* the correct way to do what we want, and IType *is* the new correct way to do what we want; Then it might be a good idea to add a type-alias to mst (marked as deprecated) to keep backwards compatibility. And that alias could be removed in the next major release.

@alisd23  That being said, if @xaviergonz adds the alias, we should hold onto this PR until the next major release of mst lands, so we don't loose backwards compatibility to a .x-Release of mst.

**Comment by xaviergonz** [comment]
Actually location is declared as a types.frozen, which was never meant to be a IComplexType, but an IType (even on versions before the change)

**Comment by freund17** [comment]
That is great news! :)
So basically, mst can stay as it is and doesn't need to adapt for our use-case; And we can simply merge this here and stay compatible to previous mst-versions.

win-win!

@xaviergonz Thanks for taking the time to clarify this!
@alisd23 Now I'm confident. Merge it! :P

**Comment by alisd23** [comment]
@xaviergonz @freund17 Thanks both of you 👍 I'm also more confident now, so I will merge.
I'll release this as a minor version (2.**2**.0) so users on an older version of `mobx-state-tree` don't get spooked.

**Pull request merged**
